### ISSUE TITLE
enums seem to break create_pydantic_model fastapi openapi compatability

### ISSUE THREAD

**Issue by trondhindenes** [piccolo-orm/piccolo#335]
Given a piccolo model containing an enum:

```
class CustomerActivationStatus(str, enum.Enum):
    Signup = "Signup"
    Active = "Active"
    Disabled = "Disabled"
    FreeSubscriptionActive = "FreeSubscriptionActive"


class Customer(Table):
    signup_guid = UUID()
    email: str = Varchar()
    created_at: datetime = Timestamptz()
    activation_status = Varchar(
        choices=CustomerActivationStatus,
        default=CustomerActivationStatus.Signup.value
    )
```

...and using `create_pydantic_model` to generate a dynamic pydantic class:
```
CustomerPatchResponseModel = create_pydantic_model(Customer)
```
..and then using that as a fastapi response model:
```
@api_v1_router.patch(
    "/customer/guid/{signup_guid}",
    response_model=CustomerPatchResponseModel,
    responses={409: {"model": None}}
)
async def patch_customer_by_guid()
    <the code>
```
Seems to break fastapi's openapi spec auto-generation:
```
Traceback (most recent call last):
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 136, in openapi
    self.openapi_schema = get_openapi(
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 387, in get_openapi
    definitions = get_model_definitions(
  File "/projects/customer-api/.venv/lib/python3.9/site-packages/fastapi/utils.py", line 28, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.Customer'>

```

If I exclude the enum field, the problem goes away:
```
CustomerPatchResponseModel = create_pydantic_model(
    Customer,
    exclude_columns=(Customer.activation_status, Customer.email,)
)
```

I'm pretty sure fastapi is able to deal with regular pydantic models including enums, so I suspect there's something about how `create_pydantic_model` generates these dynamic models.

**Comment by dantownsend** [comment]
@trondhindenes Interesting - I'll take a look.

**Comment by trondhindenes** [comment]
hm there might be something else at play here - I'm struggling to repro in another app. Will compare versions and do some more research.

**Comment by dantownsend** [comment]
@trondhindenes I've come across a similar error before when using `create_pydantic_model` twice on the same Table.

You have to make sure they have unique names using the `model_name` parameter. FastAPI doesn't like it if multiple models or types have the same name. For example:

```python
Modal1 = create_pydantic_model(Table1, model_name='Model1')
Modal2 = create_pydantic_model(Table1, model_name='Model2', all_optional=True)
```

Maybe that's it? Otherwise there could be a strange bug - I'll write some tests to try and recreate it.

**Comment by trondhindenes** [comment]
I think that's it - I found some other duplicate classnames. Strange, I was so sure the error was triggered by including that enum field.
Thanks for looking into it! I'm fine with closing this issue!

**Comment by dantownsend** [comment]
@trondhindenes No problem - if the issue occurs again let me know.

I have some ideas about how to solve this better. I will probably add this soon: https://github.com/piccolo-orm/piccolo/issues/331

**Comment by trondhindenes** [comment]
nice, that change makes a lot of sense
