### ISSUE TITLE
Failure to specify a column when using `order_by` results in a confusing error

### ISSUE THREAD

**Issue by MiguelGuthridge** [piccolo-orm/piccolo#672]
I was performing a lookup where I forgot to specify the column to order by.

```py
notifs = TNotification.objects()\
    .where(TNotification.user_to == user.id)\
    .order_by(ascending=False)\
    .run_sync()
```

This resulted in the following exception, which I don't believe accurately describes the problem.

```py
Traceback (most recent call last):
...
  File "/home/migue/Source/Ensemble/backend/models/notifications/model.py", line 142, in all
    .run_sync()
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/piccolo/query/base.py", line 247, in run_sync
    return run_sync(coroutine)
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/piccolo/utils/sync.py", line 19, in run_sync
    return asyncio.run(coroutine)
  File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/piccolo/query/base.py", line 203, in run
    results = await engine.run_querystring(
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/piccolo/engine/sqlite.py", line 548, in run_querystring
    return await self._run_in_new_connection(
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/piccolo/engine/sqlite.py", line 483, in _run_in_new_connection
    async with connection.execute(query, args) as cursor:
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/aiosqlite/context.py", line 41, in __aenter__
    self._obj = await self._coro
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/migue/Source/Ensemble/.venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: no such column: DESC
```

The experience of encountering this error would be greatly improved if Piccolo checked to ensure that the number of columns specified is at least 1.

**Comment by dantownsend** [comment]
Great idea - we should add this.
