### ISSUE TITLE
Cannot set default to `datetime.datetime.utcnow` for Timestamp column

### ISSUE THREAD

**Issue by waldner** [piccolo-orm/piccolo#697]
```
class Foo(Table):
    uuid = UUID(primary_key=True, null=False, default=uuid.uuid4, required=True)
    ts = Timestamp(default=datetime.datetime.utcnow)
```

when running `piccolo migrations new my_app --auto --trace` the following error is produced:

```
Creating new migration ...
Created tables                           1
Dropped tables                           0
Renamed tables                           0
Created table columns                    2
Dropped columns                          0
Columns added to existing tables         0
Renamed columns                          0
Altered columns                          0
The command failed.
Cannot parse: 25:177:     manager.add_column(table_class_name='Foo', tablename='foo', column_name='ts', db_column_name='ts', column_class_name='Timestamp', column_class=Timestamp, params={'default': <built-in method utcnow of type object at 0x7fce059bd8c0>, 'null': False, 'primary_key': False, 'unique': False, 'index': False, 'index_method': IndexMethod.btree, 'choices': None, 'db_column_name': None, 'secret': False})
Traceback (most recent call last):
  File "/home/cz/venv/lib/python3.10/site-packages/targ/__init__.py", line 448, in run
    command.call_with(arg_class)
  File "/home/cz/venv/lib/python3.10/site-packages/targ/__init__.py", line 229, in call_with
    asyncio.run(self.command(**cleaned_kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/cz/venv/lib/python3.10/site-packages/piccolo/apps/migrations/commands/new.py", line 219, in new
    await _create_new_migration(
  File "/home/cz/venv/lib/python3.10/site-packages/piccolo/apps/migrations/commands/new.py", line 135, in _create_new_migration
    file_contents = black.format_str(
  File "src/black/__init__.py", line 1067, in format_str
  File "src/black/__init__.py", line 1077, in _format_str_once
  File "src/black/parsing.py", line 126, in lib2to3_parse
black.parsing.InvalidInput: Cannot parse: 25:177:     manager.add_column(table_class_name='Foo', tablename='foo', column_name='ts', db_column_name='ts', column_class_name='Timestamp', column_class=Timestamp, params={'default': <built-in method utcnow of type object at 0x7fce059bd8c0>, 'null': False, 'primary_key': False, 'unique': False, 'index': False, 'index_method': IndexMethod.btree, 'choices': None, 'db_column_name': None, 'secret': False})
```

On the other hand, setting `datetime.datetime.now` as default is accepted.

**Comment by sinisaos** [comment]
@waldner I think you should use the [Timestamptz](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/column_types.html#timestamptz) column type (default is UTC) and everything should be fine. Sorry if I'm wrong.

**Comment by dantownsend** [comment]
The reason this error happens is when we create the migrations we have to serialise the column parameters. `datetime.datetime.now` and `datetime.datetime.utcnow` are really difficult values to serialise.

It slips through our serialisation code, because it's not a method, not a function, doesn't have a module!! It's weird:

```python
>>> inspect.isfunction(datetime.datetime.now)
False
>>> inspect.ismethod(datetime.datetime.now)
False
>>> datetime.datetime.now.__module__
None
>>> datetime.datetime.now is datetime.datetime.now
False
```

This is the relevant code which we need to fix (we need a special case for datetime.datetime.now / datetime.datetime.utcnow).

https://github.com/piccolo-orm/piccolo/blob/1f036ad37fc5290412809988537dc606bbaf3cf6/piccolo/apps/migrations/auto/serialisation.py#L480

Anyway ... what @sinisaos says is correct. If you use `Timestamptz` instead, then it uses `datetime.datetime.now(tz=datetime.timezone.utc)` by default, which is the same as `datetime.datetime.utcnow()`.

**Comment by waldner** [comment]
Thanks. I wanted to avoid `Timestamptz` because that results in a column of type `timestamp with time zone` in the db, whereas I wanted to keep everything naive (for reasons outside the scope of this comment, mostly related to foreign tools or libraries that want to do "the right thing" when they get an aware timestamp). So I'll probably remove the default value from the ORM schema, and just set it on the fly whenever data is written/updated to the db.
