### ISSUE TITLE
the number of query arguments cannot exceed 32767

### ISSUE THREAD

**Issue by lgblkb** [piccolo-orm/piccolo#733]
### Environment:
* OS: Ubuntu 22.10
* Using venv: true
* **piccolo==0.101.0**
* **DB: postgres:15**

### What I'm trying to do:
* I dumped one table (~100k rows) into fixture.json (~45MB).
* Then I'm trying to load the fixture back into DB (For testing production setup).

### Problem:
* Running 
`piccolo fixtures load /storage/picco_flow/fixtures.json` results in 
`asyncpg.exceptions._base.InterfaceError: the number of query arguments cannot exceed 32767` error.

### My thoughts:
* Apparently, piccolo fixture is designed for small size of "prepopulation" data.
* In my case, my initial DB seeding data contains ~100k rows. Hence, I can't use piccolo fixture.

### Question:
* What would be the proper way to seed my DB with ~100k rows?
 
### Full stack trace:
<pre>
(picco_flow) lgblkb@PC:~/PycharmProjects/picco_flow$ <b>piccolo fixtures load /storage/picco_flow/fixtures.json --trace </b>
The command failed.
the number of query arguments cannot exceed 32767
Traceback (most recent call last):
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/targ/__init__.py", line 448, in run
    command.call_with(arg_class)
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/targ/__init__.py", line 229, in call_with
    asyncio.run(self.command(**cleaned_kwargs))
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/piccolo/apps/fixtures/commands/load.py", line 80, in load
    await load_json_string(contents)
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/piccolo/apps/fixtures/commands/load.py", line 70, in load_json_string
    await table_class.insert(*data[table_class]).run()
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/piccolo/query/base.py", line 203, in run
    results = await engine.run_querystring(
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/piccolo/engine/postgres.py", line 435, in run_querystring
    return await current_transaction.connection.fetch(
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/asyncpg/connection.py", line 620, in fetch
    return await self._execute(
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
  File "/home/lgblkb/mambaforge/envs/picco_flow/lib/python3.10/site-packages/asyncpg/connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 183, in bind_execute
  File "asyncpg/protocol/prepared_stmt.pyx", line 124, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions._base.InterfaceError: the number of query arguments cannot exceed 32767
</pre>

**Comment by dantownsend** [comment]
Ah, good point. I haven't tried loading fixtures this large before.

We just need to change this code, so it inserts smaller chunks:

https://github.com/piccolo-orm/piccolo/blob/1092d490a51401e42bc253bdb477aa96fe656c18/piccolo/apps/fixtures/commands/load.py#L68-L70

**Comment by dantownsend** [comment]
Should be fixed in the next Piccolo version.
