### ISSUE TITLE
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation

### ISSUE THREAD

**Issue by powellnorma** [piccolo-orm/piccolo#807]
Hi, sometimes I get the above exception. Once it happens, all following DB Queries are raising this exception, so I have to restart the entire web app. The Trace-Back looks something like this:

```python
  File "/app/app.py", line 359, in process_list
    async with DB.transaction():
  File "/piccolo/piccolo/engine/postgres.py", line 173, in __aenter__
    self.connection = await self.engine.get_new_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/piccolo/piccolo/engine/postgres.py", line 389, in get_new_connection
    return await asyncpg.connect(**self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "/venv/lib64/python3.11/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation
```

**Comment by dantownsend** [comment]
Looks like some other people have encountered similar problems with asyncpg: https://github.com/MagicStack/asyncpg/issues/309

What's interesting about your traceback is you're making a direct connection to Postgres, and not acquiring a connection from a pool. With a pool I can imagine many potential causes (a connection being killed off for being too old etc), but as it's a fresh connection it's quite strange.

Is there any chance that your app has exhausted all connections to Postgres? By default it's set to something like 100. You would expect a different exception than `ConnectionDoesNotExistError` though.

**Comment by powellnorma** [comment]
> Is there any chance that your app has exhausted all connections to Postgres?

I don't think so, it just randomly seems to happen every now and then.

Do you think it would be feasible to handle this in this library ? So that in [`get_new_connection`](https://github.com/piccolo-orm/piccolo/blob/36e80f58b87822244e405736be141e68b5ae7fa4/piccolo/engine/postgres.py#L462) we somehow restart (?) asyncpg, if we get `ConnectionDoesNotExistError`? Because currently I still need to restart the server manually.

I think adding it to this library would have the benefit that not everyone needs to write his/her own workaround to this bug which seems to possibly affect everyone(?) using the postgres engine, even though seldom. 

What do you think?

**Comment by dantownsend** [comment]
> Do you think it would be feasible to handle this in this library ? So that in [get_new_connection](https://github.com/piccolo-orm/piccolo/blob/36e80f58b87822244e405736be141e68b5ae7fa4/piccolo/engine/postgres.py#L462) we somehow restart (?) asyncpg, if we get ConnectionDoesNotExistError? Because currently I still need to restart the server manually.

I'm not sure. We could try fetching another connection after a short `asyncio.sleep`.

Restarting the server will kill all existing connections. I'm not sure if we could do it in a graceful way.

What kind of stack are you running? I read through this thread again: https://github.com/MagicStack/asyncpg/issues/309 and it seems like the following could be true:

* `uvloop` is somehow to blame
* The Postgres server is under resourced
* Some kind of network middleware is killing connections

Are you running any real long transactions?

I had a quick look through the Sentry logs for some of my apps, and I've seen `TimeoutError` when trying to get a connection, but not so much of `ConnectionDoesNotExistError`.

**Comment by powellnorma** [comment]
> What kind of stack are you running

I indeed use uvloop. I don't use docker, the Starlette App and Postgress both run "natively" on the system.

In the postgres log it says:
```
LOG:  could not receive data from client: Connection reset by peer
```

> Are you running any real long transactions?

I don't think so, max should be ~1-2s

What I wonder about.. The `ConnectionDoesNotExistError` to me seems to indicate that a "connection reuse" is happening on some  level. Maybe it is possible to force asyngpg to really use a new connection? Currently `get_new_connection` uses `asyncpg.connect`. Maybe the stored connections are available via some private attribute, which we could clear as a workaround?

**Comment by dantownsend** [comment]
> I indeed use uvloop. I don't use docker, the Starlette App and Postgres both run "natively" on the system.

So the stack isn't likely to be causing the problem. It could be uvloop ... but kind of hard to test if the error only occurs sporadically.

> I don't think so, max should be ~1-2s
Transactions don't sound like the problem either.

> The ConnectionDoesNotExistError to me seems to indicate that a "connection reuse" is happening on some level.
Or that the connection is killed part way through an operation.

> Maybe the stored connections are available via some private attribute, which we could clear as a workaround?
I would need to look more into the internals of asyncpg.

At what point does the error get raised? Immediately after `get_new_connection`, or part way through a query?

**Comment by powellnorma** [comment]
What is interesting is that this Exception, once it was raised a single time, seems to be raised for all subsequent queries. In the asyncpg log however the line `Connection reset by peer` is only shown once.

And [here](https://github.com/MagicStack/asyncpg/issues/309#issuecomment-423506987) someone was able to solve this problem by changing the keepalive of tcp connections. So this are clues that I think indicate that there could be a faulty/closed connection in some sort of cache - But maybe it has other causes. 

> Immediately after get_new_connection, or part way through a query?

I think it happens during get_new_connection, when trying to connect to postgres. The first stack trace looks the same as the ones following it

**Comment by powellnorma** [comment]
> but kind of hard to test if the error only occurs sporadically

Today I tested:
1. Cancel Task that does DB Operation (insert) after different delays
2. Do many inserts concurrently
3. Do simple DB Operation (insert) after increasing delays (15s to >1h)

Sadly, none of these were able to reproduce this. With  1. I sometimes got `asyncio.exceptions.InvalidStateError:`, with 2. I got `asyncpg.exceptions.TooManyConnectionsError:`.

However I realized that my App wasn't using connection pooling at all, since this has to be enabled manually. Since this `ConnectionDoesNotExistError` seems to have been thrown when creating new connections, I hope that this also reduces the (overall) chance of this bug occurring (since now, way fewer new connections should need to be created)

**Comment by stronk7** [comment]
Following on this, I had my application working ok without connection pools and today I just tried adding this (following the documentation, that presents is as a transparent drop-in) to see how it performs (disclaimer, I see the 5 connections in the database):

```python
    # We are going to use ORM services, point to its configuration file.
     os.environ["PICCOLO_CONF"] = "moodlebot_mcp.piccolo_conf"
    ...
    ...
+    # Piccolo database connections pool (only if Postgres engine)
+    engine = engine_finder()
+    if engine and isinstance(engine, PostgresEngine):
+        await engine.start_connection_pool(min_size=5, max_size=10)
+    else:
+        logger.error("Error: Database engine not found. Exiting.")
+        sys.exit(1)
```

And, since then, every database operation, is failing with an error similar to the reported here (if something is different is that in the stack trace, I see how `self.pool.acquire() as connection` is being called, so I assume that it's trying to use the pool.

Worth noting the runtime exception at the beginning ...

Here it's the stack trace:

```log
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/piccolo/utils/sync.py", line 24, in run_sync
    return asyncio.run(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 191, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/faststream/_internal/endpoint/subscriber/usecase.py", line 364, in process_message
    await h.call(
  File "/opt/venv/lib/python3.12/site-packages/faststream/_internal/endpoint/subscriber/call_item.py", line 146, in call
    result = await call(message)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/faststream/middlewares/acknowledgement/middleware.py", line 77, in consume_scope
    return await call_next(msg)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/faststream/middlewares/logging.py", line 63, in consume_scope
    return await call_next(msg)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/faststream/_internal/endpoint/call_wrapper.py", line 90, in call_wrapped
    return await self._wrapped_call(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/faststream/_internal/di/config.py", line 135, in decode_wrapper
    return await func(msg)
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/fast_depends/use.py", line 170, in injected_wrapper
    return await real_model.asolve(  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/fast_depends/core/model.py", line 339, in asolve
    response = await run_async(self.call, *final_args, **final_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/fast_depends/utils.py", line 48, in run_async
    return await cast(Callable[P, Awaitable[T]], func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/moodlebot_central/ai/actions/process_completion_request/action.py", line 83, in run
    completion.user = " ".join(db_get_user_name_from_user_id(completion.user_id))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/cachetools/_cached.py", line 196, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/app/moodlebot_central/util.py", line 204, in db_get_user_name_from_user_id
    ).first().run_sync()
              ^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/piccolo/query/proxy.py", line 31, in run_sync
    return run_sync(self.run(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/piccolo/utils/sync.py", line 29, in run_sync
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/piccolo/query/methods/select.py", line 97, in run
    rows = await self.query.run(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/piccolo/query/methods/select.py", line 673, in run
    results = await super().run(node=node, in_pool=in_pool)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/piccolo/query/base.py", line 193, in run
    return await self._run(node=node, in_pool=in_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/piccolo/query/base.py", line 175, in _run
    results = await engine.run_querystring(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/piccolo/engine/postgres.py", line 554, in run_querystring
    response = await self._run_in_pool(query, query_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/piccolo/engine/postgres.py", line 514, in _run_in_pool
    async with self.pool.acquire() as connection:
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 1031, in __aexit__
    await self.pool.release(con)
  File "/opt/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 905, in release
    return await asyncio.shield(ch.release(timeout))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 228, in release
    raise ex
  File "/opt/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 218, in release
    await self._con.reset(timeout=budget)
  File "/opt/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 1562, in reset
    await self.execute(reset_query)
  File "/opt/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 349, in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 360, in query
  File "asyncpg/protocol/protocol.pyx", line 745, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress
2025-11-13T16:26:07.061Z ERROR [asyncio] Future exception was never retrieved
future: <Future finished exception=ConnectionDoesNotExistError('connection was closed in the middle of operation')>
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation
```

Ciao :-)

**Comment by dantownsend** [comment]
@stronk7 It looks like this line is the problem:

```
File "/app/moodlebot_central/util.py", line 204, in db_get_user_name_from_user_id
    ).first().run_sync()
```

Are you able to refactor that method so it doesn't use `run_sync`? i.e. it uses `await` instead.

```python
await some_query.first()
```

I'm not sure why this error is emerging while the connection pool is active, and not when the connection pool is disabled.

**Comment by stronk7** [comment]
Uhm... but I'm using `run_sync()` there because the `db_get_user_name_from_user_id()` function is `@cached`, hence cannot use it in an asynchronous way.

Anyway, I'll remove the caching to test it that enables the pool to be used, no matter I think the (sync) use case above is a valid one.

And yes, it only happens once I configured the pool. Without that, it's working perfectly, so far.

Thanks for the prompt answer, I'll report back soon... ciao :-)

**Comment by Skelmis** [comment]
Perhaps something like a cache library that supports async could help you?

https://github.com/aio-libs/async-lru
