### ISSUE TITLE
Creating new migration ... The command failed

### ISSUE THREAD

**Issue by Fidel-C** [piccolo-orm/piccolo#828]
This is the error I have been getting each time I run `piccolo migrations new app_name --auto`
Creating new migration ... The command failed. 'TableConfig' object has no attribute '__name__' For a full stack trace, use --trace
![Screenshot (24)](https://github.com/piccolo-orm/piccolo/assets/61763700/b59df759-a00e-42f4-a235-332a4382ae80)
![Screenshot (25)](https://github.com/piccolo-orm/piccolo/assets/61763700/b22f810e-f741-4b19-b5be-905c01468bc1)
![Screenshot (23)](https://github.com/piccolo-orm/piccolo/assets/61763700/55ee4517-c6d7-456a-91e3-a075afc70511)

The error does not occur when I omit `--auto` but I end up with an empty migration file as a result.
Images of some parts of my database setup below!

**Comment by dantownsend** [comment]
Can you run `piccolo migrations new app_name --auto --trace` (not the `--trace` at the end). It'll give you a full stack trace.

Hopefully that'll help us figure out what's going on.

**Comment by Fidel-C** [comment]
> Can you run `piccolo migrations new app_name --auto --trace` (note the `--trace` at the end). It'll give you a full stack trace.
> 
> Hopefully that'll help us figure out what's going on.



This is the output of running  `piccolo migrations new app_name --auto --trace`

Creating new migration ...
The command failed.
'TableConfig' object has no attribute '__name__'
Traceback (most recent call last):
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\targ\__init__.py", line 448, in run
    command.call_with(arg_class)
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\targ\__init__.py", line 229, in call_with
    asyncio.run(self.command(**cleaned_kwargs))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\piccolo\apps\migrations\commands\new.py", line 240, in new
    await _create_new_migration(
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\piccolo\apps\migrations\commands\new.py", line 123, in _create_new_migration
    alter_statements = await AutoMigrationManager(
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\piccolo\apps\migrations\commands\new.py", line 188, in get_alter_statements
    current_diffable_tables = [
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\piccolo\apps\migrations\commands\new.py", line 190, in <listcomp>
    class_name=i.__name__,
AttributeError: 'TableConfig' object has no attribute '__name__'

**Comment by dantownsend** [comment]
If you look in your `piccolo_app.py` files, it looks like one of them contains a `TableConfig` instead of a `Table`.

**Comment by Fidel-C** [comment]
Thanks a lot but after making some changes to my `piccolo_app.py` and `app.py` files this is the error now,

Creating new migration ...
The command failed.
'list' object has no attribute '__name__'
Traceback (most recent call last):
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\targ\__init__.py", line 448, in run
    command.call_with(arg_class)
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\targ\__init__.py", line 229, in call_with
    asyncio.run(self.command(**cleaned_kwargs))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\piccolo\apps\migrations\commands\new.py", line 240, in new
    await _create_new_migration(
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\piccolo\apps\migrations\commands\new.py", line 123, in _create_new_migration
    alter_statements = await AutoMigrationManager(
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\piccolo\apps\migrations\commands\new.py", line 188, in get_alter_statements
    current_diffable_tables = [
  File "C:\Users\Fidelc\Desktop\prog\python_projects\fastapi_projects\bookingApp\venv\lib\site-packages\piccolo\apps\migrations\commands\new.py", line 190, in <listcomp>
    class_name=i.__name__,
AttributeError: 'list' object has no attribute '__name__'


![Screenshot (28)](https://github.com/piccolo-orm/piccolo/assets/61763700/4b3e3160-7e2b-4e46-846e-3a91a054b248)
![Screenshot (29)](https://github.com/piccolo-orm/piccolo/assets/61763700/a691ee8c-126a-4ca6-bc14-3584680b0fe3)

**Comment by dantownsend** [comment]
If you remove the square brackets around table_finder it should work.

**Comment by dantownsend** [comment]
I'll close this for now, as I think we've found the solution.

**Comment by Fidel-C** [comment]
Thanks a lo it worked
