### ISSUE TITLE
Column definition not parsed in class Table

### ISSUE THREAD

**Issue by bedi7** [piccolo-orm/piccolo#903]
Hi,

Lastly I tried to play with piccolo-orm.
I've created simple table and tried to create it in DB, just in first step I hit situation incomprehensible to me.
Some columns are not recognized by poccolo.

Code snipped:
```python
from time import sleep

from piccolo.engine.postgres import PostgresEngine
from piccolo.table import Table
from piccolo.columns.column_types import BigSerial, Varchar, Email


DB = PostgresEngine(
    config={
        'host': 'localhost',
        'database': 'my_db',
        'user': 'postgres',
        'password': 'postgres',
        "port": 5432},
    log_queries=True,
    log_responses=True)


class User(Table, db=DB, tablename='users'):
    # id = BigSerial(primary_key=True, unique=True, auto_update=True),
    secret = Varchar(length=255, secret=True),
    bio = Varchar(length=255),
    username = Varchar(length=255, unique=True)
    email = Email(length=255, unique=True)


print("Dump, SQL create table:")
print(User.create_table(if_not_exists=True))#
sleep(1)
print("\nError about not existing columns:")
print("Here1: ", User(username="user1",
                      email="user1@aaa.com",
                      secret="pass",
                      bio="bio"))

```

Received error:
```python
python -m poetry run issue.py

Dump, SQL create table:
['CREATE TABLE IF NOT EXISTS "users" ("id" SERIAL PRIMARY KEY NOT NULL, "username" VARCHAR(255) UNIQUE NOT NULL DEFAULT \'\', "email" VARCHAR(255) UNIQUE NOT NULL DEFAULT \'\')']

Error about not existing columns:
Traceback (most recent call last):
  File "../issue.py", line 31, in <module>
    print("Here1: ", User(username="user1",
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "../lib/python3.12/site-packages/piccolo/table.py", line 439, in __init__
    raise ValueError(f"Unrecognized columns - {unrecognised_list}")
ValueError: Unrecognized columns - ['secret', 'bio']

Process finished with exit code 1
```
This code was tested on WSL Ubuntu 22.04.3 and on Windows machine with the same errors output
Packages versions
```
[tool.poetry.dependencies]
python = "^3.12"
piccolo = {extras = ["postgres"], version = "^1.1.1"}
asyncpg = "^0.29.0"
```

**Comment by dantownsend** [comment]
From the DDL for creating the table that you posted:

```
['CREATE TABLE IF NOT EXISTS "users" ("id" SERIAL PRIMARY KEY NOT NULL, "username" VARCHAR(255) UNIQUE NOT NULL DEFAULT \'\', "email" VARCHAR(255) UNIQUE NOT NULL DEFAULT \'\')']
```

It looks like it just created the `id`, `username` and `email` columns - not the `secret` and `bio` columns.

Maybe try deleting the table from the database, and try it again?

Also, be careful with this `User.create_table(if_not_exists=True)` it doesn't do anything unless you do the following:

```python
await User.create_table(if_not_exists=True)
# OR
User.create_table(if_not_exists=True).run_sync()
```

**Comment by dantownsend** [comment]
I think I see your problem - there's commas after some of the columns:

```python
class Users(Table, db=DB):
    # id = BigSerial(primary_key=True, unique=True, auto_update=True),
    secret = Varchar(length=255, secret=True),   # <- here
    bio = Varchar(length=255),   # <- here
    username = Varchar(length=255, unique=True)
    email = Email(length=255, unique=True)
```
